S3 batch
aws/aws-lambda-java-libs pull request #179
Opened 2020-10-21 15:05 UTC by msailes

*Issue #, if available:*

https://github.com/aws/aws-lambda-java-libs/issues/177

*Description of changes:*

Event and response objects for S3 Batch operations.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-10-21 15:41 UTC, david-kingsbury-bah requested changes
After making the one field name change (result VS results), I was able to successfully run an S3 Batch Operations job that invokes a Lambda written using these models.

2020-10-21 15:41 UTC, david-kingsbury-bah commented on aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/S3BatchResponse.java
> +    private List<Result> result;
```suggestion
    private List<Result> results;
```

2020-10-21 15:41 UTC, david-kingsbury-bah commented on aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/S3BatchResponse.java
> +    private List<Result> result;
Plural "results"

2020-10-21 15:44 UTC, msailes commented on aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/S3BatchResponse.java
> +    private List<Result> result;
fixed.

2020-10-21 15:56 UTC, david-kingsbury-bah commented
Since we have the ResultCode enum now, I'm thinking S3BatchOpResponse.treatMissingKeysAs should be of type ResultCode.

```
private ResultCode treatMissingKeysAs;
```

### The following are ideas that might go too far for this library; let me know what you think.

We could default treatMissingKeysAs to PermanentFailure, as this is _likely_ the value _most_ people will use.

```
private ResultCode treatMissingKeysAs = ResultCode.PermanentFailure;
```

We could have a special constructor to seed a response instance. These must be set for the response to be considered valid. If one does not want to use this, they can use the other constructors.

```
    public S3BatchResponse(final S3BatchEvent request) {
        this.invocationSchemaVersion = request.getInvocationSchemaVersion();
        this.invocationId = request.getInvocationId();
        this.results = Collections.singletonList(
                Result.builder()
                        .withTaskId(request.getTasks().get(0).getTaskId())
                        .withResultCode(ResultCode.Succeeded)
                        .build()
        );
    }
```

2020-10-21 16:05 UTC, msailes commented
Hi David,

Great feedback! What about something like this in the S3BatchResponse.java class.

```java
public static S3BatchResponseBuilder fromS3BatchEvent(S3BatchEvent s3BatchEvent) {
        return S3BatchResponse.builder()
                .withInvocationId(s3BatchEvent.getInvocationId())
                .withInvocationSchemaVersion(s3BatchEvent.getInvocationSchemaVersion());
}
```

I think I'd be nervous adding any default behavior which might have a negative impact. I don't know this area of the platform that well, so I would definitely appreciate any feedback.

Thanks,

Mark

2020-10-21 16:23 UTC, david-kingsbury-bah commented
The `fromS3BatchEvent` method looks great!

I think the question now is should `fromS3BatchEvent` go as far as my example and create a single `Result` with the Task ID set.

- S3 Batch Ops expects the response result Task ID to match what was passed in through the request (`S3BatchEvent`). I suspect this allows S3 Batch Ops to do many concurrent invocations and still be able to gather and sort results.
- S3 Batch Ops only sends 1 task, and expects only 1 result. Here is a snippet from their docs
   ```
   # S3 batch operations currently only passes a single task at a time in the array of tasks.
   task = event['tasks'][0]
   ```

I'm on the fence. The API _allows_ for multiple tasks and results, however it is certainly 1 task per event today.

2020-10-21 17:16 UTC, msailes commented
In my opinion no. 

If all that was required was the task id it would make sense. But the user will still have to add their own values for resultCode and resultString. So I don't think there is much to be gained.

2020-10-22 10:19 UTC, msailes commented
I've also tested this now.

2020-10-22 13:31 UTC, david-kingsbury-bah approved these changes

2020-10-28 10:23 UTC, carlzogh approved these changes
LGTM!

2020-10-28 10:24 UTC, merged

2020-10-28 10:24 UTC, carlzogh commented
Thanks @msailes and @david-kingsbury-bah! :)

2020-10-28 12:54 UTC, david-kingsbury-bah commented
Excellent!

Resolved #177