Graalvm support
aws/aws-lambda-java-libs pull request #255
Opened 2021-07-08 15:03 UTC by msailes

*Issue #, if available:*

*Description of changes:*
GraalVM config and regression test.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-16 16:48 UTC, szab100 commented
Hi @msailes, what is this PR waiting for? We are facing with the same issues when trying to use spring native with graalvm..

2021-09-16 18:26 UTC, msailes commented
@szab100 if possible could you contact me at msailes@amazon.co.uk

Thanks,

2021-09-22 13:55 UTC, msailes commented
@szab100 could you 👍  this issue please. https://github.com/aws/aws-lambda-java-libs/issues/272

2022-04-05 10:47 UTC, stejsj commented
@msailes should the runtime client work with graalvm? We use scala and are trying to use your approach to get a native-image running to reduce cold start and resource requirements. 

Sadly I get this error 
START RequestId: 3a579869-9b96-46d7-9ce4-8c049a79d6c1 Version: $LATEST
[appconfig agent] 2022/04/05 10:36:21 INFO AppConfig Lambda Extension 2.0.45
[appconfig agent] 2022/04/05 10:36:21 INFO serving on localhost:2772
starting outage runtime...
Failed to load the native runtime interface client library aws-lambda-runtime-interface-client.glibc.so. Exception: null
Failed to load the native runtime interface client library aws-lambda-runtime-interface-client.musl.so. Exception: null
EXTENSION	Name: AppConfigAgent	State: Ready	Events: [SHUTDOWN,INVOKE]
END RequestId: 3a579869-9b96-46d7-9ce4-8c049a79d6c1
REPORT RequestId: 3a579869-9b96-46d7-9ce4-8c049a79d6c1	Duration: 253.23 ms	Billed Duration: 254 ms	Memory Size: 2048 MB	Max Memory Used: 56 MB	
XRAY TraceId: 1-624c1ba4-441854bd0da7b1425ca04379	SegmentId: 14184b9f35ddfe28	Sampled: true	

Eventhough I tried to manually include those two libraries as native-image resource args
example -H:IncludeResources="+baseDirectory.value / "src" / "main" / "resources" / "META-INF" / "resources" / "aws-lambda-runtime-interface-client.glibc.so"

We have been struggling quite a lot getting this to work, any thoughts, hints or ideas?

Thanx in advance
Steffen

2022-05-26 14:06 UTC, carlzogh requested changes

2022-05-26 14:06 UTC, carlzogh commented on aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/graalvm/LambdaEventsGraalVMFeature.java
> +    public static final String EVENTS_PACKAGE_NAME = "com.amazonaws.services.lambda.runtime.events";
I think we should make this generic enough for it to be reused across all our libraries in this project, and move it out of the runtime addressable scope. It should be a build-only class that is not exposed in the library.

This is essentially boilerplate code that will traverse our libraries and determine what the appropriate `native-image` config is, so we don't really need a copy of it per project.

2022-05-26 14:06 UTC, carlzogh commented on aws-lambda-java-runtime-interface-client/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/jni-config.json
> +]
Can this be auto-generated like `reflect-config.json`?

2022-05-26 14:06 UTC, carlzogh commented on aws-lambda-java-runtime-interface-client/test/integration/codebuild-graalvm/buildspec.os.amazoncorretto.yml
> +      - >
Some parts of this script have been refactored, we should update this

2023-01-03 18:00 UTC, closed without merging