Fix os compatibility tests by enabling multi-platform build and testing
aws/aws-lambda-java-libs pull request #334
Opened 2022-04-29 15:36 UTC by zsombor-balogh

*Issue #, if available:*

*Description of changes:*

**Enable multi-arch testing**

Currently compatibility tests are failing when trying to build multi-arch JNI libs:

```
Build JNI libraries:
     [exec] Compiling the native library for target glibc on architecture x86_64 using Docker platform linux/amd64
     [exec] The command '/bin/sh -c rpm --import https://yum.corretto.aws/corretto.key &&     curl -L -o /etc/yum.repos.d/corretto.repo https://yum.corretto.aws/corretto.repo' returned a non-zero code: 1
     [exec] tar: This does not look like a tar archive
     [exec] tar: Skipping to next header
     [exec] tar: src/aws-lambda-runtime-interface-client.so: Not found in archive
     [exec] tar: Exiting with failure status due to previous errors
```
* set up a multi-arch build environment prior to building the Runtime Interface Client and running the tests:
  * install necessary emulator,
  * install docker-buildx plugin
* reenable multi-arch RIC build on alpine and amazoncorretto distros
* add `PLATFORM` to the build matrix, build platform specific test images and run integ tests for both x86_64 and arm64
* run smoke tests for both x86_64 and arm64
* disable multi-arch RIC build on AL1 (available only for x86_64) 

**Clean up EOL/ESM os versions from os compatibility tests**
* clean up EOL oss:
  * alpine 3.9, 3.10, 3.11, 3.12 
  * centos 8
  * ubuntu 16.04 (ESM)
* add more recent versions
  * alpine 3.13, 3.14, 3.15
  * debian bullseye
  * ubuntu 21.10, 22.04 

**Source base images from Amazon ECR Public**

* pull test and build images from Amazon ECR Public instead of Docker Hub (some of the images were already sourced from public ECR)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-29 16:46 UTC, carlzogh requested changes

2022-04-29 16:46 UTC, carlzogh commented on aws-lambda-java-runtime-interface-client/test/integration/codebuild-local/test_all.sh
>      done
nit: indentation

2022-04-29 19:16 UTC, zsombor-balogh commented on aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.alpine.yml
> +      - docker buildx install
Yeah, that's a fair point! Extracted the multi-arch environment setup for now, will extract the other shared parts, which not related to this change, in a separate PR.

2022-04-30 09:16 UTC, carlzogh approved these changes

2022-04-30 10:10 UTC, smirnoal approved these changes

2022-05-03 07:31 UTC, merged